version: 1.2
workflows:
   - name: "celseq2"
     subclass: WDL
     primaryDescriptorPath: /celseq2.wdl
    #  testParameterFiles:
    #  - /test_params/sceqtl_inputs.json
     filters: 
        branches: 
          - main
          - dev
        tags: 
          - /.*/
